.plugin.c: 
	cd $(top_builddir) \
	  && $(SHELL) ./config.status $(subdir)/$@ \
		$(am__depfiles_maybe)

.plugin.h: 
	cd $(top_builddir) \
	  && $(SHELL) ./config.status $(subdir)/$@ \
		$(am__depfiles_maybe)

Makefile: $(top_srcdir)/m4/Makefile.plugin

