#-*-makefile-*-

include ../Makefile.base

sources = dnode.sh print.sh print_.sh

all: $(sources)

#.PHONY: $(SHPREFIX).dir
install: $(SHPREFIX).dir $(sources:%.sh=$(SHPREFIX)/%.sh)

dnode.sh: dnode.sh.pre
print_.sh: print_.sh.pre

$(SHPREFIX)/dnode.sh: dnode.sh ; $(installexec)
$(SHPREFIX)/print.sh: print.sh ; $(installexec)
$(SHPREFIX)/print_.sh: print_.sh ; $(installexec)

clean: ; -rm dnode.sh print_.sh

