.plugin.c:
	m4 $(M4DEBUG) -P "-I$(srcdir)" \
		-DPLUGIN_NAME=`echo "$@" | sed -e 's,.c$$,,'` \
		-DPLUGIN_HEADER=no \
		-DPLUGIN_LOCAL=$(PLUGIN_LOCAL) \
		"$(DM_PLUGINDATA_DIR)/plugin.m4" > "$@.tmp"
	mv "$@.tmp" "$@"

.plugin.h:
	m4 $(M4DEBUG) -P "-I$(srcdir)" \
		-DPLUGIN_NAME=`echo "$@" | sed -e 's,.h$$,,'` \
		-DPLUGIN_HEADER=yes \
		-DPLUGIN_LOCAL=$(PLUGIN_LOCAL) \
		"$(DM_PLUGINDATA_DIR)/plugin.m4" > "$@.tmp"
	mv "$@.tmp" "$@"


