#-*-makefile-*-

include ../Makefile.base

sources = dvt-emacs.tex dvt-3.0.tex

all: $(sources:%.tex=%.pdf)

#.PHONY: $(DOCPREFIX).dir
install: $(DOCPREFIX).dir $(sources:%.tex=$(DOCPREFIX)/%.pdf)

$(DOCPREFIX)/dvt-emacs.pdf: dvt-emacs.pdf ; $(installfile)
$(DOCPREFIX)/dvt-3.0.pdf: dvt-3.0.pdf ; $(installfile)

clean: ; -rm *.pdf

