Document: dm
Title: Debian dm Manual
Author: <insert document author here>
Abstract: This manual describes what dm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dm/dm.sgml.gz

Format: postscript
Files: /usr/share/doc/dm/dm.ps.gz

Format: text
Files: /usr/share/doc/dm/dm.text.gz

Format: HTML
Index: /usr/share/doc/dm/html/index.html
Files: /usr/share/doc/dm/html/*.html

  
