#! /usr/bin/env sh

dgen="$1/dgen"
dirin="$2"
basein="$3"
baseout="$4"
baseboot="`basename $4 .built`"

dictin=`basename "$3" .d`

${dgen} <<EOF \
	&& echo Remember to cp "${dirin}/${baseout}" "${dirin}/${baseboot}" 2>&1
(${dirin}/) (${basein}) fromfiles 
${dictin} begin 
  (${dirin}/) (${baseout}) all 
end 
quit
EOF
