#-*-makefile-*-

include ../Makefile.base

sources = cajal2.img form_1.ps form_2.ps graf.ps graf_1.ps gray.ps \
	monday.ps struct.ps text.ps thursday.ps thursday_cajal2.ps \
	topdf.sh tuesday.ps

thursday.ps: thursday.ps.pre
tuesday.ps: tuesday.ps.pre

all: $(sources)

install: $(PSPREFIX).dir $(sources:%=$(PSPREFIX)/%)

$(PSPREFIX)/%: % ; $(installfile)

clean: ; -rm thursday.ps tuesday.ps


