#-*-makefile-*-

include ../Makefile.base

sources = dm1.c dm2.c dm3.c dm4.c dm5.c dm6.c dm7.c dm8.c dm9.c \
	  dmnum.c dsp1.c dsp2.c

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(MAKECMDGOALS),distclean)
include $(sources:%.c=%.dep)  dnode.dep dvt.dep
endif
endif

dvt: $(sources:%.c=%.o) dvt.o
dnode: $(sources:%.c=%.o) dnode.o

$(PREFIX)/dvt: dvt ; $(installexec)
$(PREFIX)/dnode: dnode ; $(installexec)

all: dvt dnode

install: $(PREFIX).dir $(PREFIX)/dvt $(PREFIX)/dnode

clean: ; -rm *.o *.dep 
